account: mail@protonmail.com
password: v3rS3cr3t
checkIntervalMinutes: 5
forwarding:
  - address: mail@protonmail.com
    recipients:
      - mail@gmail.com
  - address: mail@pm.me
    recipients:
      - mail@gmail.com
